# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0010_allow_field_marks_be_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='teamorigin',
            options={'verbose_name': 'Team origin'},
        ),
        migrations.AlterField(
            model_name='fight',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Completed')], default=0),
        ),
        migrations.AddField(
            model_name='fight',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
    ]
